version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

sphinx:
    configuration: docs/conf.py

formats: all

python:
    version: "3.12"
    install:
        - method: pip
          path: .
        - method: setuptools
          path: .

conda:
    environment: environment.yml